stages:
  - build
  - lint
  - test
  - security

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  DOCKER_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"

# Common configuration to be extended
.common_config:
  image: "${DOCKER_IMAGE_NAME}"
  cache:
    paths:
      - .pip-cache/

include:
  - .gitlab/ci/build.yml
  - .gitlab/ci/test.yml
  - .gitlab/ci/security.yml
